### ISSUE TITLE
Bloated bundle size

### ISSUE THREAD

**Issue by osdiab** [rahafoundation/raha-web-app#100]
Using source-map-explorer we see that our bundle size is a little embarrasing for how tiny and simple this app is.

Looks like Firebase and FontAwesome are taking up a ton of space, probably not being tree shaked properly. Maybe we're including them wrong somehow or tree-shaking is not configured quite right (though i think `create-react-app` should be set up properly for us?)

<img width="1274" alt="screen shot 2018-04-12 at 2 08 24 am" src="https://user-images.githubusercontent.com/1890926/38667555-8f05304a-3df6-11e8-9442-38e3930a7e28.png">

**Comment by tinaroh** [comment]
Probably irrelevant now that we are on mobile.
