### ISSUE TITLE
$ in member id URL sometimes terminates URL from being clickable

### ISSUE THREAD

**Issue by osdiab** [rahafoundation/raha-web-app#107]
On my friend's Samsung Galaxy S5 running the Textra SMS app, the link

https://raha.io/m/mark.ulrich$2777

Got interpreted as a link ending at ulrich; and then $2777 was omitted from it.

Consider using a different scheme for deduplicating member ids.

**Comment by rahulgi** [comment]
Transitioned to "." instead of "$".
