### ISSUE TITLE
Google Login fails from messenger on mobile

### ISSUE THREAD

**Issue by kem226** [rahafoundation/raha-web-app#11]
When trying to log in on mobile following a messenger link we get a disallowed_useragent error

**Comment by markulrich** [comment]
Seems Facebook login also fails ... we really need to put up some "sorry Raha.io does not work in WebView, open in browser please!" message otherwise this makes for a very bad first experience

**Comment by markulrich** [comment]
Also does not work if people are using the Google app instead of Safari/Chrome on mobile

**Comment by tinaroh** [comment]
We moved to SMS login, so issue is not relevant anymore
