### ISSUE TITLE
Unable to select my .mov file to upload 

### ISSUE THREAD

**Issue by kellywang** [rahafoundation/raha-web-app#115]
I recorded a video (8.5 mb) on my iphone and transferred it to my computer, can't select it to upload to join though :( In the screenshot, it's the IMG_9947.mov

<img width="922" alt="screen shot 2018-04-17 at 1 14 59 pm" src="https://user-images.githubusercontent.com/3347054/38885641-9fe627bc-4241-11e8-942c-0582b206ffa0.png">

**Comment by markulrich** [comment]
First community reported issue!!! 😍😍😍

As of today we only support mp4 :/
Does it work if you convert it? Maybe using some tool like https://www.zamzar.com/convert/mov-to-mp4/ ?

**Comment by rahulgi** [comment]
I don't think we're going to fix this, as we are moving to using invite videos taken through the mobile application, rather than taken and uploaded separately. Thanks for reporting though, @kellywang!
