### ISSUE TITLE
Add ability to merge google/facebook/github login to phone login

### ISSUE THREAD

**Issue by osdiab** [rahafoundation/raha-web-app#157]
You can link multiple accounts with JavaScript using Firebase, [as described here](https://firebase.google.com/docs/auth/web/account-linking). 

We are trying to switch entirely to SMS login, so after logging in with Google/Facebook/Github, you should be directed to a new page that won't let you continue until you add an SMS account, and link it to the account. Should we also unlink the Google/Facebook/Github account as well?

**Comment by rahulgi** [comment]
Closing with #161.
