### ISSUE TITLE
Account migration does not tell you to log in

### ISSUE THREAD

**Issue by markulrich** [rahafoundation/raha-web-app#172]
When visiting https://web.raha.app/accountMigration using an in private tab it does not force you to log in

**Comment by rahulgi** [comment]
Ah yeah -- I think this might be related to the PR that I tried to land but then had you revert b/c stuff seemed to be broken? Want to finish the async invite flow first - then I can take a look at this

**Comment by markulrich** [comment]
Fixed in https://github.com/rahafoundation/raha-web-app/pull/176
