### ISSUE TITLE
Mobile log in only supports +1 numbers right now.

### ISSUE THREAD

**Issue by rahulgi** [rahafoundation/raha-web-app#192]
This impacts both SSO and account migration.

**Comment by redro** [comment]
Little note:
I didn't understand why I had to verify my mobile phone number a 2nd time. As I set up my account, I already had to verify with my mobile phone. I don't understand the purpose of a 2nd verification?

**Comment by rahulgi** [comment]
@redro, ah, you triggered an interesting thought in my mind... The reason is that the marketplace button redirects to your web browser where you're not signed in. However, I think we could actually sign you in automatically from the app when we redirect you to the web browser. Created https://github.com/rahafoundation/raha-mobile-app/issues/408 to track this as well. Thanks for the note!

**Comment by rahulgi** [comment]
@redro this should be fixed.. lmk if you still have issues logging in.
