### ISSUE TITLE
Perf tests

### ISSUE THREAD

**Issue by markulrich** [rahafoundation/raha-web-app#45]
The current size of main.js is already 300 KB! Would be nice to track this in tests and make sure it does not increase much more. Also measuring time to render for important pages would be ideal.

**Comment by markulrich** [comment]
Update: now main.js is 501 KB as of https://github.com/rahafoundation/raha.io/commit/1597e3bd41e57244a5d68521457fe23af5f70dfc, need to keep this under control!

**Comment by rahulgi** [comment]
Closing for now since web app perf is not a priority.
